name: deploy-manifests

on:
  push:
    branches: [master]
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ DIGIALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing # your kube cluster name
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
