name: deploy-auth

on:
  push:
    branches: [master]
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t unicdev/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push unicdev/auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGIALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing # your kube cluster name
      - run: kubectl rollout restart deployment auth-depl
