name: tests-payments

on:
  push:
    branches: [master]
    paths:
      - 'payments/**'
  pull_request:
    branches: [master]
    paths:
      - 'payments/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm i && npm run test:ci
