name: tests-auth

on:
  push:
    branches: [master]
    paths:
      - 'auth/**'
  pull_request:
    branches: [master]
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && npm i && npm run test:ci
